
server:
  port: 8080
  servlet:
    contextPath: /sw-planets-api

feign:
  hystrix:
    enabled: true
  httpclient:
    max-connections: 1
    connection-timeout: 2000

spring:
  cache:
    type: redis
  application:
    name: sw-planets-api
  data:
    mongodb:
      host: localhost
      port: 27017

    redis:
      host: localhost
      port: 6379
      ttl: 86400
      database: 1

application:
  starwars:
    url: http://swapi.co/api

