
server:
  port: 8080
  servlet:
    contextPath: /sw-planets-api

feign:
  httpclient:
    max-connections: 1
    connection-timeout: 2000

spring:
  cache:
    type: redis
  application:
    name: sw-planets-api
  data:
    mongodb:
      host: localhost
      port: 27017

application:
  starwars:
    url: http://swapi.co/api

redis:
  host: 'localhost'
  port: 6379
  ttl: 86400
  database: 1